[supervisord]
nodaemon=true
logfile=/var/log/astrocat/supervisord.log
pidfile=/tmp/supervisord.pid

[program:uvicorn]
command=uvicorn app.main:app --host 0.0.0.0 --port 8089 --workers 4
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery_worker]
command=celery -A app.worker worker --loglevel=info --concurrency=4 -Q indexer,thumbnails,celery
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery_beat]
command=celery -A app.worker beat --loglevel=info --schedule=/tmp/astrocat/celerybeat-schedule
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
