"""Add rating_flushed_at to images

Revision ID: c258328513d4
Revises: 8c2e5f6a3d1b
Create Date: 2026-02-02 14:29:59.039340+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c258328513d4'
down_revision: Union[str, None] = '8c2e5f6a3d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('rating_flushed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'rating_flushed_at')
    # ### end Alembic commands ###
