"""Add messier columns

Revision ID: 15ec32f5cfc8
Revises: 
Create Date: 2026-01-26 17:08:50.170346+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15ec32f5cfc8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messier_catalog', sa.Column('axis_ratio', sa.Float(), nullable=True))
    op.add_column('messier_catalog', sa.Column('position_angle', sa.Float(), nullable=True))
    op.add_column('messier_catalog', sa.Column('pgc_designation', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messier_catalog', 'pgc_designation')
    op.drop_column('messier_catalog', 'position_angle')
    op.drop_column('messier_catalog', 'axis_ratio')
    # ### end Alembic commands ###
