"""
Astrometry.net Sidecar Parser
Parses .wcs, .ini, or .axy sidecar files generated by plate solvers (local or online).
"""

import configparser
from pathlib import Path
from typing import Dict, Any


class SidecarParser:
    """Parses WCS data from sidecar files."""
    
    @staticmethod
    def parse(image_path: Path) -> Dict[str, Any]:
        """
        Look for a sidecar file for the given image and parse it.
        Checks: .wcs, .ini, .axy
        """
        # Common sidecar extensions
        for ext in ['.wcs', '.new', '.ini']:
            sidecar = image_path.with_suffix(ext)
            if sidecar.exists():
                if ext == '.ini':
                    return SidecarParser._parse_ini(sidecar)
                elif ext in ['.wcs', '.new']:
                    return SidecarParser._parse_fits_wcs(sidecar)
                
        return None

    @staticmethod
    def _parse_fits_wcs(path: Path) -> Dict[str, Any]:
        """Parse WCS data from a .wcs or .fits sidecar file."""
        from astropy.io import fits
        from astropy.wcs import WCS
        try:
            with fits.open(path) as hdul:
                header = hdul[0].header
                wcs = WCS(header)
                if wcs.is_celestial:
                    n1 = header.get("NAXIS1", 0)
                    n2 = header.get("NAXIS2", 0)
                    center = wcs.pixel_to_world(n1/2, n2/2)
                    
                    # Return both the summary fields for DB and the raw header for full SIP
                    return {
                        "ra_center": float(center.ra.degree),
                        "dec_center": float(center.dec.degree),
                        "pixel_scale": float(wcs.proj_params[0] * 3600 if hasattr(wcs, 'proj_params') else 0), # Simplified
                        "is_plate_solved": True,
                        "wcs_type": "SIDECAR_WCS",
                        "raw_header": {k: v for k, v in header.items() if k not in ['HISTORY', 'COMMENT']}
                    }
        except Exception:
            pass
        return None

    @staticmethod
    def _parse_ini(path: Path) -> Dict[str, Any]:
        """Parse Astrometry.net style INI files."""
        config = configparser.ConfigParser()
        try:
            config.read(path)
            
            # Usually under [Astrometry] or [Calibration]
            # This is a hypothetical structure, adjust based on actual sidecar format
            section = None
            if "Astrometry" in config:
                section = config["Astrometry"]
            elif "Field" in config:
                section = config["Field"]
                
            if section:
                return {
                    "ra_center": float(section.get("ra", section.get("RA", 0))),
                    "dec_center": float(section.get("dec", section.get("DEC", 0))),
                    "pixel_scale": float(section.get("pixscale", section.get("PIXSCALE", 0))),
                    "radius_degrees": float(section.get("radius", section.get("RADIUS", 0))),
                    "is_plate_solved": True,
                    "wcs_type": "SIDECAR_INI"
                }
        except Exception:
            pass
            
        return None
