"""
Astrometry.net Sidecar Parser
Parses .wcs, .ini, or .axy sidecar files generated by plate solvers (local or online).
"""

import configparser
import math
from pathlib import Path
from typing import Dict, Any


class SidecarParser:
    """Parses WCS data from sidecar files."""
    
    @staticmethod
    def parse(image_path: Path) -> Dict[str, Any]:
        """
        Look for a sidecar file for the given image and parse it.
        Checks: .wcs, .ini, .axy
        """
        # Common sidecar extensions
        for ext in ['.wcs', '.new', '.ini']:
            sidecar = image_path.with_suffix(ext)
            if sidecar.exists():
                if ext == '.ini':
                    return SidecarParser._parse_ini(sidecar)
                elif ext in ['.wcs', '.new']:
                    return SidecarParser._parse_fits_wcs(sidecar)
                
        return None

    @staticmethod
    def _parse_fits_wcs(path: Path) -> Dict[str, Any]:
        """Parse WCS data from a .wcs or .fits sidecar file."""
        from astropy.io import fits
        from astropy.wcs import WCS
        try:
            with fits.open(path) as hdul:
                header = hdul[0].header
                wcs = WCS(header)
                if wcs.is_celestial:
                    n1 = header.get("NAXIS1", 0)
                    n2 = header.get("NAXIS2", 0)
                    center = wcs.pixel_to_world(n1/2, n2/2)
                    
                    # Return both the summary fields for DB and the raw header for full SIP
                    return {
                        "ra_center": float(center.ra.degree),
                        "dec_center": float(center.dec.degree),
                        "pixel_scale": float(wcs.proj_params[0] * 3600 if hasattr(wcs, 'proj_params') else 0), # Simplified
                        "is_plate_solved": True,
                        "wcs_type": "SIDECAR_WCS",
                        "raw_header": {k: v for k, v in header.items() if k not in ['HISTORY', 'COMMENT']}
                    }
        except Exception:
            pass
        return None

    @staticmethod
    def _parse_ini(path: Path) -> Dict[str, Any]:
        """Parse a plate-solve .ini: Astrometry.net ([Astrometry] section) or ASTAP (flat KEY=VALUE)."""
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except Exception:
            return None
        if text.lstrip().startswith("["):
            return SidecarParser._parse_astrometry_ini(text)
        return SidecarParser._parse_astap_ini(text)

    @staticmethod
    def _parse_astrometry_ini(text: str) -> Dict[str, Any]:
        """Astrometry.net / nova job INI: ra/dec/pixscale/radius/orientation under [Astrometry]."""
        config = configparser.ConfigParser()
        try:
            config.read_string(text)

            # Usually under [Astrometry] or [Calibration]
            section = None
            if "Astrometry" in config:
                section = config["Astrometry"]
            elif "Field" in config:
                section = config["Field"]

            if section:
                result = {
                    "ra_center": float(section.get("ra", section.get("RA", 0))),
                    "dec_center": float(section.get("dec", section.get("DEC", 0))),
                    "pixel_scale": float(section.get("pixscale", section.get("PIXSCALE", 0))),
                    "radius_degrees": float(section.get("radius", section.get("RADIUS", 0))),
                    "is_plate_solved": True,
                    "wcs_type": "SIDECAR_INI"
                }
                # Same key the online solver task stores as rotation_degrees.
                orientation = section.get("orientation", section.get("ORIENTATION", "")).strip()
                if orientation:
                    result["rotation"] = float(orientation) % 360.0
                return result
        except Exception:
            pass

        return None

    @staticmethod
    def _parse_astap_ini(text: str) -> Dict[str, Any]:
        """
        ASTAP solve INI: section-less KEY=VALUE lines. A solve has PLTSOLVD=T plus
        CRVAL1/2 (centre, deg), CD matrix (deg/px) or CDELT1/2, and CROTA1/2.
        Failed solves carry PLTSOLVD=F and no WCS keys.
        """
        values = {}
        for line in text.splitlines():
            key, sep, val = line.partition("=")
            if sep:
                values[key.strip().upper()] = val.strip()

        if values.get("PLTSOLVD", "").upper() != "T":
            return None

        def num(key):
            try:
                return float(values[key])
            except (KeyError, ValueError):
                return None

        ra, dec = num("CRVAL1"), num("CRVAL2")
        if ra is None or dec is None:
            return None

        cd12, cd22 = num("CD1_2"), num("CD2_2")
        cd11, cd21 = num("CD1_1"), num("CD2_1")
        rotation = None
        pixel_scale_deg = None
        if cd12 is not None and cd22 is not None:
            # Same convention as FitsExtractor._extract_wcs for CD-matrix headers.
            rotation = math.degrees(math.atan2(-cd12, cd22))
            if cd11 is not None and cd21 is not None:
                pixel_scale_deg = math.sqrt(abs(cd11 * cd22 - cd12 * cd21))
        if rotation is None:
            rotation = num("CROTA2")
            if rotation is None:
                rotation = num("CROTA1")
        if pixel_scale_deg is None:
            cdelt2 = num("CDELT2")
            pixel_scale_deg = abs(cdelt2) if cdelt2 else None

        result = {
            "ra_center": ra,
            "dec_center": dec,
            "is_plate_solved": True,
            "wcs_type": "SIDECAR_INI",
        }
        if pixel_scale_deg:
            result["pixel_scale"] = pixel_scale_deg * 3600.0
        if rotation is not None:
            result["rotation"] = rotation % 360.0
        return result
